### ISSUE TITLE
Release 0.3.1 of PyTNG

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/pytng#108]
A release of pytng is necessary in order to allow for py3.12 support - this is blocking the core library here: https://github.com/MDAnalysis/mdanalysis/pull/4327

**Comment by hmacdope** [comment]
Ill cut now?

**Comment by IAlibay** [comment]
@hmacdope what's your release procedure? It should match the new deployment workflow

**Comment by IAlibay** [comment]
New release procedure should be:

1. Make & push tags
2. Check GH action for testpypi push worked fine
3. Make release
4. Check GH action for pypi push worked fine

**Comment by hmacdope** [comment]
Normally, cut tag on main, pull, then push to PyPi from my own computer, I assume the new workflow makes it easier?

**Comment by IAlibay** [comment]
> Normally, cut tag on main, pull, then push to PyPi from my own computer, I assume the new workflow makes it easier?

yeah you don't need to do any of that anymore, wheel building should be automatic - assuming the workflow doesn't have any bugs (it'll probably fail the first time around knowing how these things go).

**Comment by hmacdope** [comment]
Cutting directly on github will trigger or do i need to actually `push` the tags from local.

**Comment by IAlibay** [comment]
@hmacdope 

Yes, just doing this will work:

```bash
git tag -m "release 0.3.1 of pytng" v0.3.1
git push --tags origin
```

Then when CI passes you can just do a release using that new tag.

**Comment by IAlibay** [comment]
Looks like the wheel upload went fine: https://test.pypi.org/project/pytng/#files

Should be good to cut a release.

**Comment by hmacdope** [comment]
Legendary, thanks so much. Good practice for me to understand the no-local workflow as well.

**Comment by hmacdope** [comment]
Done and tested.

**Comment by IAlibay** [comment]
@hmacdope you're probably going to need to update the conda-forge recipe quite a bit because of the numpy pins, iirc the current defaults aren't the same as what conda-forge expects.

**Comment by IAlibay** [comment]
I don't think I'm a maintainer for that recipe but if you ping me for review I can add the necessary changes.

**Comment by hmacdope** [comment]
Cheers, will do. Thanks for sorting this out I was very slow, my apologies.
