### ISSUE TITLE
num_frames is broken 

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/pytng#26]
https://redmine.gromacs.org/issues/2937

**Comment by orbeckst** [comment]
@hmacdope is this an issue that we can close here?

**Comment by richardjgowers** [comment]
I think this might be to do with the difference between number of timesteps simulated and the number of frames stored in the file

**Comment by hmacdope** [comment]
Yep I think possible confusion upstream resulted in the GMX redmine issue.

I will close for now.
