### ISSUE TITLE
How to specify what data is read out at each frame?

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/pytng#30]
Design questions

How will we figure out what data is accessible at each frame? Not all trajectories have positions and box at every frame interval, let alone other data like forces, velocities which can be written at whatever interval you specify. (A whole list of available blocks is in the `tng_io.h`). 

Thus we need to find a way to not try and pull all the info at every step.

FYI 

The TNG syntax for "frames" is also a bit confusing as it really is the number of actual md steps (`nsteps` in gromacs).
Data is written with a `stride_length` ie data is deposited every stride_length "frames". I just thought I would bring this up as it tripped my up repeatedly.

**Comment by orbeckst** [comment]
The TRR format is also extremely flexible with each frame (= timestep) being free to provide whatever it feels like (x, v, f). Maybe looking at the MDA TRR code might help?

**Comment by hmacdope** [comment]
Thanks Oliver i'll have a look. :)

**Comment by richardjgowers** [comment]
@hmacdope I think maybe a good solution is to be lazy about it.  Make the TNGFile iteration only iterate through block ids, this returning a `Block` object which holds a `tng_block_t` you can query for data.  I took a quick skim through the code and I can't tell if we can do this lazily using the public API or if we need to dive a little :)

A "trajectory reader" will then iterate through the TNGFile blocks and skip blocks that aren't relevant, i..e just a simple filter around the natural iteration of the TNGFile
