### ISSUE TITLE
Build error on Python 3.8.5 Numpy 1.18.1 Cython 0.29.21

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/pytng#33]
Build with the above versions of numpy, cython and python don't work. seems related to a cython issue [#2938](https://github.com/cython/cython/issues/2938#issue-438804384)

We might need to pin to versions below this.

**Comment by orbeckst** [comment]
By all means, go ahead and add pins.

**Comment by orbeckst** [comment]
Still an issue?

**Comment by hmacdope** [comment]
3.8 Travis build would say no, but I should double check.
