### ISSUE TITLE
Check coverage of grand-canonical simulations.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/pytng#45]
In theory the TNG format can do grand-canonical simulation. We currently do not support this or check for it. This should be addressed in tests as well. 

Some questions about support for this upstream? unsure if how this works in GROMACS or otherwise.

**Comment by orbeckst** [comment]
Best thing to do is to fail early. One question is how one can detect as early as possible that the data are from GCMD.

**Comment by richardjgowers** [comment]
I not aware of anyone producing GC trajectories yet. Maybe best currently to fail early until there's a real source of these files?
