### ISSUE TITLE
Packaging for conda and pip

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/pytng#46]
When the API is stable we should package for conda and pip!

**Comment by orbeckst** [comment]
should -> must ... otherwise it won't really be used

**Comment by hmacdope** [comment]
Let me know when you think we have stabilised enough to package.

**Comment by orbeckst** [comment]
Release early and often!

You can always start with 0.01 ;-)

**Comment by hmacdope** [comment]
I'll start prepping for a release candidate.
