### ISSUE TITLE
release 0.2

### ISSUE THREAD

**Issue by richardjgowers** [MDAnalysis/pytng#5]
Things todo for the release
 - [x] pypi
 - [x] conda package
 - [x] coverage
 - [x] docs
 - [x] remove warning/"do not use" from the docs 
 - [x] gh pages for docs
 - [x] zenodo badge

**Comment by richardjgowers** [comment]
docs are auto-deployed off the master branch to http://www.mdanalysis.org/pytng

**Comment by orbeckst** [comment]
@hmacdope the current docs at https://www.mdanalysis.org/pytng/ do not reflect the latest API changes. Are they currently properly deployed?

**Comment by hmacdope** [comment]
@orbeckst Deploying off the 3.6 build is failing, as I think our credentials or token is invalid for some reason. I can try and fix but no Github REST expert.

**Comment by hmacdope** [comment]
If it's a problem with the token itself I can't fix, as I do not have permissions.

**Comment by orbeckst** [comment]
I updated the token (and migrated to travis-ci.com, see #53).

**Comment by orbeckst** [comment]
... doc building works again https://travis-ci.com/github/MDAnalysis/pytng/jobs/387305651

**Comment by hmacdope** [comment]
thanks for fixing @orbeckst.

**Comment by hmacdope** [comment]
@orbeckst is the zenodo stuff managed by MDA? Probably best if you do it.

**Comment by orbeckst** [comment]
https://zenodo.org/account/settings/github/repository/MDAnalysis/pytng — but we won't have a badge or DOI until the first release. If you cut a alpha or rc then let me know or go to the above page. It will create a badge and we can then include the badge in proper first release.

**Comment by hmacdope** [comment]
I don't have the right permissions.

**Comment by orbeckst** [comment]
@hmacdope can you create releases?

**Comment by orbeckst** [comment]
p.s.: Try creating one on GitHub https://github.com/MDAnalysis/pytng/releases/new, use a tag **v0.01-alpha** and make a pre-release.

**Comment by hmacdope** [comment]
I'll wait for #57 to be merged. :)

**Comment by orbeckst** [comment]
Back on track for a release?

**Comment by hmacdope** [comment]
Yep tracking well again! Just pip and conda packaging (#46) and zenodo badge to go.

**Comment by orbeckst** [comment]
Do a pre-release, alpha, or rc1. This will trigger zenodo. 

You can also use the pre-release for the first pypi upload. (You'll need `twine` for that... I have notes for releasing eg in https://github.com/MDAnalysis/pmda/wiki/Developer-Guide or https://github.com/MDAnalysis/GridDataFormats/wiki/Developer-Guide#release-management , at least as a starting point)

The conda-forge package will build from the pypi sources. I can't remember how to create a new conda-forge package... see https://conda-forge.org/, I think it starts with forking the recipes.

**Comment by orbeckst** [comment]
I assigned you @hmacdope , you should have the pleasure to release/unleash your creation on the world ;-)

**Comment by hmacdope** [comment]
Thanks @orbeckst, wouldn't have been possible without you or @richardjgowers.
I'll be sure to let out an evil chuckle or two.

**Comment by hmacdope** [comment]
@orbeckst @richardjgowers, now on PyPi if you want to give it a try.

**Comment by orbeckst** [comment]
You can't change revisions... let's just roll with it. It's just a number. 

You can add both of us as package owners, just so that there are enough people who can do maintenance if necessary.

**Comment by hmacdope** [comment]
@orbeckst and @richardjgowers your PyPi usernames are? :)

**Comment by orbeckst** [comment]
Oliver.Beckstein on pypi

**Comment by orbeckst** [comment]
https://pypi.org/user/richard.j.gowers

**Comment by hmacdope** [comment]
Conda package now almost ready.

**Comment by orbeckst** [comment]
The badge in markdown 

[![DOI](https://zenodo.org/badge/92180386.svg)](https://zenodo.org/badge/latestdoi/92180386)

```markdown
[![DOI](https://zenodo.org/badge/92180386.svg)](https://zenodo.org/badge/latestdoi/92180386)
```

or in reST
```reST
.. image:: https://zenodo.org/badge/92180386.svg
   :target: https://zenodo.org/badge/latestdoi/92180386
```

Add one of these two to the README.

**Comment by hmacdope** [comment]
Thanks @orbeckst! Do you need to cut a new DOI every release?

**Comment by orbeckst** [comment]
No. It does it automatically as soon as you make a release on GitHub.

If you use the above links, they will auto-update and always point to the last archived release.

**Comment by orbeckst** [comment]
Release is currently blocked on https://github.com/conda-forge/pytng-feedstock/issues/5 (pypy 3.6 conda builds are failing).

**Comment by hmacdope** [comment]
:(

**Comment by hmacdope** [comment]
@orbeckst fixed now :)

**Comment by orbeckst** [comment]
Hooray! Good to go then?

**Comment by hmacdope** [comment]
Yes! I'll tag the new release and upload.

**Comment by hmacdope** [comment]
All done! Thank you both so much, it's been a pleasure. I look forward to more releases all over the MDA ecosystem.

**Comment by orbeckst** [comment]
Hooray! Thank you @hmacdope
