### ISSUE TITLE
build_sphinx is not working

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/pytng#61]
`build_sphinx` is not working while the sphinx makefile is.

Note that adding a build sphinx config in setup.cfg broke doc deployment(See #60).

**Comment by orbeckst** [comment]
Is the `python setup.py build_sphinx` still broken?

Presumably, Travis is not a concern anymore since we use GitHub actions and the standard doc deployment workflow.

**Comment by hmacdope** [comment]
Yep still not working. Some sphinx module import pathing trick that I cannot work out.

**Comment by hmacdope** [comment]
There appears to be some kind of dual level import going on .

import pytng exposes pytng.classes and pytng.pytng which for some reason sphinx has a problem with.
possibly related to the extension being called `pytng.pytng` rather than just pytng.

**Comment by pradyunsg** [comment]
https://github.com/sphinx-doc/sphinx/issues/9595

The relevant command is now considered deprecated, and will be removed in a future Sphinx release.

**Comment by hmacdope** [comment]
Oh well that is unexpected but good news. I will move to remove that as the build step.

**Comment by orbeckst** [comment]
@hmacdope then we should replace `python setup.py build_sphinx` with the appropriate invocation of [`sphinx-build`](https://www.sphinx-doc.org/en/master/man/sphinx-build.html).

**Comment by hmacdope** [comment]
Closing as not used in build.
