### ISSUE TITLE
MAINT: Switch from Travis to Github actions as CI providers

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/pytng#80]
Follow up from: https://github.com/MDAnalysis/mdanalysis/issues/3036

As our Travis allocation is organisation wide, it might be best to switch over to Github actions where possible.

**Comment by hmacdope** [comment]
@IAlibay This should be complete now. Someone with the relevant keys can turn off travis for PyTNG.

**Comment by hmacdope** [comment]
@IAlibay if you have turned off Travis for PyTNG I can close? :)

**Comment by IAlibay** [comment]
I'll look into turning off travis now. do you want to update the README badge? The build currently points to Travis.

**Comment by IAlibay** [comment]
Well that returned fast :( Looks like I need admin priviledges on Travis, probably @richardjgowers or @orbeckst might know who has that access?

**Comment by hmacdope** [comment]
Renaming `.travis.yml` to `.disable.travis.yml` seemed to do the job stopping it running. I will close for now.
