### ISSUE TITLE
data frames attribute does not appear to work for all files.

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/pytng#95]
the `FileIterator.n_data_frames` attr doesn't appear to work for a trajectory that has gone through TRJCONV

**Comment by orbeckst** [comment]
What's the corresponding `gmx trjconv` command that you used to generate the misbehaving trajectory?

Is this a problem with trjconv or with pytng?

**Comment by hmacdope** [comment]
I need to dig in further to both the Cython in PyTNG and the C++ in TNG itself to see where the error is being generated. IIRC the call used to get the number of frames (`tng_util_num_frames_with_data_of_block_id_get`) is not strictly part of the public TNG API, so may not work under all circumstances.

**Comment by hmacdope** [comment]
Alternately `trjconv` may not write the correct information. **it is also worth noting that this was done in the absences of a tpr file . ** this may possibly affect the final result and is worth checking.

**Comment by hmacdope** [comment]
this is because we were enforcing that the current  step was mod 0 with the  `block stride`

```cython
        if self.step % stride_length != 0:
            return TNG_CRITICAL
```

I will remove this requirement.
